# Generated by Django 4.2.7 on 2024-09-14 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('es_efectivo', models.BooleanField(default=False)),
                ('b_Q100', models.IntegerField(default=0)),
                ('b_Q50', models.IntegerField(default=0)),
                ('b_Q20', models.IntegerField(default=0)),
                ('b_Q10', models.IntegerField(default=0)),
                ('b_Q5', models.IntegerField(default=0)),
                ('m_100c', models.IntegerField(default=0)),
                ('m_50c', models.IntegerField(default=0)),
                ('m_25c', models.IntegerField(default=0)),
                ('m_10c', models.IntegerField(default=0)),
                ('m_5c', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBancoVirtual.cuenta')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBancoVirtual.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha', models.DateField()),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PersonaBeneficiaria', to='MiBancoVirtual.subcuenta')),
                ('ordenante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PersonaOrdenante', to='MiBancoVirtual.subcuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha', models.DateField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiBancoVirtual.Transaccion.beneficiario+', to='MiBancoVirtual.subcuenta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MiBancoVirtual.categoria')),
                ('ordenante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiBancoVirtual.Transaccion.ordenante+', to='MiBancoVirtual.subcuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha', models.DateField()),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MiBancoVirtual.categoria')),
                ('subcuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBancoVirtual.subcuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha', models.DateField()),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MiBancoVirtual.categoria')),
                ('subcuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBancoVirtual.subcuenta')),
            ],
        ),
    ]
