# Generated by Django 4.2.7 on 2024-10-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0004_alter_cuenta_monto_real'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='monto_real',
            new_name='saldo_real',
        ),
    ]
