# Generated by Django 4.2.7 on 2024-10-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0005_rename_monto_real_cuenta_saldo_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
