# Generated by Django 4.2.7 on 2024-12-19 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0007_remove_transaccionprogramada_abonado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccionprogramadadetalle',
            name='Abonado',
        ),
        migrations.RemoveField(
            model_name='transaccionprogramadadetalle',
            name='FechaLimite',
        ),
        migrations.RemoveField(
            model_name='transaccionprogramadadetalle',
            name='MetaCantidad',
        ),
        migrations.AddField(
            model_name='transaccionprogramada',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccionprogramada',
            name='FechaLimite',
            field=models.DateField(null=True),
        ),
    ]
