# Generated by Django 4.2.7 on 2024-12-19 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MiBancoVirtual', '0008_remove_transaccionprogramadadetalle_abonado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionprogramada',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
