"""
Django settings for FinanzaVirtual project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

import os
import json

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
config_path = BASE_DIR / "db_config.appsettings.json"

with open(config_path) as f:
    db_config = json.load(f)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1pe&ps*jrv(prj5r1duu3eum$+4&$zabok!zlb%##w@e79kzs*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', True)

# DB_NAME = os.getenv('DB_NAME',)
# DB_USER = os.getenv('DB_USER',)
# DB_PASSWORD = os.getenv('DB_PASSWORD',)
# DB_HOST = os.getenv('DB_HOST',)
# DB_DATABASE_PORT = os.getenv('DB_DATABASE_PORT',)

# VARIABLES_DB = {
#     "DB_NAME": DB_NAME,
#     "DB_USER": DB_USER,
#     "DB_PASSWORD": DB_PASSWORD,
#     "DB_HOST": DB_HOST,
#     "DB_DATABASE_PORT": DB_DATABASE_PORT,
# }

# VARIABLES_DB_NULAS = [k for k, v in VARIABLES_DB.items() if v is None]

# if VARIABLES_DB_NULAS:
#     raise Exception(f"Hacen falta las variables de entorno: {VARIABLES_DB_NULAS}")

APPEND_SLASH = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    "fabriciomejia.pythonanywhere.com",
    'restaurantelaantigua.pythonanywhere.com',
    'finanzavirtual.onrender.com',
    '142.93.254.184',
    '142.93.254.184:8000',
]


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Core.Services.MiBancoVirtual',
    # 'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://142.93.254.184',
    'http://142.93.254.184:8000',
    'http://192.168.0.99:5173',
]

ROOT_URLCONF = 'FinanzaVirtual.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend', 'dist'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FinanzaVirtual.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': db_config
}

# DATABASES = {
#     'default': {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": DB_NAME,
#         "USER": DB_USER,
#         "PASSWORD": DB_PASSWORD,
#         "HOST": DB_HOST,
#         "PORT": DB_DATABASE_PORT,
#         "OPTIONS": {
#             "options": "-c search_path=produccion"
#         }
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Puedes quitarlo si quieres forzar solo JWT
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # O AllowAny si lo quieres público
    ],
    'DATETIME_FORMAT': "%d-%m-%Y",
    'DATETIME_INPUT_FORMATS': ["%d-%m-%Y %H:%M:%S"],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

CORS_ALLOW_CREDENTIALS = True

LANGUAGE_CODE = 'es-gt'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'frontend/dist/'
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "dist",
]
# TEMPLATES[0]['DIRS'] = 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/login"