# Generated by Django 4.2.7 on 2024-09-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionProgramada',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('FechaLimite', models.DateField(null=True)),
                ('MetaCantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Abonado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiBancoVirtual.Transaccion.beneficiario+', to='MiBancoVirtual.subcuenta')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MiBancoVirtual.categoria')),
                ('Ordenante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiBancoVirtual.Transaccion.ordenante+', to='MiBancoVirtual.subcuenta')),
            ],
        ),
    ]
