# Generated by Django 4.2.7 on 2024-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0002_transaccionprogramada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='monto_real',
            field=models.IntegerField(null=True),
        ),
    ]
