# Generated by Django 4.2.7 on 2024-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0003_cuenta_monto_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='monto_real',
            field=models.IntegerField(default=0),
        ),
    ]
