# Generated by Django 4.2.7 on 2025-01-31 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0010_perfil_agregartotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuentaBeneficiaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_cuenta_beneficiaria', to='MiBancoVirtual.cuenta'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cuentaOrdenante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_cuenta_ordenante', to='MiBancoVirtual.cuenta'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='perfilBeneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_perfil_beneficiario', to='MiBancoVirtual.perfil'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='perfilOrdenante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_perfil_ordenante', to='MiBancoVirtual.perfil'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='beneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_beneficiario', to='MiBancoVirtual.subcuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='ordenante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_ordenante', to='MiBancoVirtual.subcuenta'),
        ),
    ]
