# Generated by Django 4.2.7 on 2025-07-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0012_remove_ingreso_categoria_remove_ingreso_subcuenta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='agregarTotal',
            new_name='AgregarTotal',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='id',
            new_name='IdPerfil',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
