# Generated by Django 5.2.4 on 2025-08-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0013_rename_agregartotal_perfil_agregartotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='b_Q10',
            new_name='BQ10',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='b_Q100',
            new_name='BQ100',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='b_Q20',
            new_name='BQ20',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='b_Q5',
            new_name='BQ5',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='b_Q50',
            new_name='BQ50',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='es_efectivo',
            new_name='EsEfectivo',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='id',
            new_name='IdCuenta',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='m_100c',
            new_name='M100c',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='m_10c',
            new_name='M10c',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='m_25c',
            new_name='M25c',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='m_50c',
            new_name='M50c',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='m_5c',
            new_name='M5c',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='saldo_real',
            new_name='SaldoReal',
        ),
    ]
