# Generated by Django 5.2.4 on 2025-08-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0014_rename_b_q10_cuenta_bq10_rename_b_q100_cuenta_bq100_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='fecha',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='fechaCreacion',
            new_name='FechaCreacion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='categoria',
            new_name='IdCategoria',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='cuentaBeneficiaria',
            new_name='IdCuentaBeneficiaria',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='cuentaOrdenante',
            new_name='IdCuentaOrdenante',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='perfilBeneficiario',
            new_name='IdPerfilBeneficiario',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='perfilOrdenante',
            new_name='IdPerfilOrdenante',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='id',
            new_name='IdTransaccion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='monto',
            new_name='Monto',
        ),
    ]
