# Generated by Django 5.2.4 on 2025-08-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0015_rename_descripcion_transaccion_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='id',
            new_name='IdCuenta',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
