# Generated by Django 5.2.4 on 2025-08-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0016_rename_id_categoria_idcuenta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='IdCuenta',
            new_name='IdCategoria',
        ),
    ]
