# Generated by Django 5.2.4 on 2025-10-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0017_rename_idcuenta_categoria_idcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='AgregarTotal',
            new_name='SumaDisponible',
        ),
        migrations.RenameField(
            model_name='transaccionprogramada',
            old_name='Id',
            new_name='IdTransaccionProgramada',
        ),
        migrations.RenameField(
            model_name='transaccionprogramada',
            old_name='Usuario',
            new_name='IdUsuario',
        ),
        migrations.RenameField(
            model_name='transaccionprogramadadetalle',
            old_name='Id',
            new_name='IdTransaccionProgramadaDetalle',
        ),
        migrations.AddField(
            model_name='categoria',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
