# Generated by Django 5.2.7 on 2026-06-16 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0018_rename_agregartotal_perfil_sumadisponible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccionprogramadadetalle',
            old_name='Categoria',
            new_name='IdCategoria',
        ),
        migrations.AddField(
            model_name='transaccionprogramada',
            name='FechaSiguienteVez',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaccionprogramada',
            name='FechaUltimaVez',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaccionprogramadadetalle',
            name='Fecha',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='transaccionprogramadadetalle',
            name='IdCuentaBeneficiaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_beneficiaria', to='MiBancoVirtual.cuenta'),
        ),
        migrations.AddField(
            model_name='transaccionprogramadadetalle',
            name='IdCuentaOrdenante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_ordenante', to='MiBancoVirtual.cuenta'),
        ),
        migrations.AddField(
            model_name='transaccionprogramadadetalle',
            name='IdPerfilBeneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_beneficiario', to='MiBancoVirtual.perfil'),
        ),
        migrations.AddField(
            model_name='transaccionprogramadadetalle',
            name='IdPerfilOrdenante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_ordenante', to='MiBancoVirtual.perfil'),
        ),
    ]
