# Generated by Django 5.2.4 on 2026-06-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0019_rename_categoria_transaccionprogramadadetalle_idcategoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Activo',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='IdPerfil',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='SumaDisponible',
            new_name='suma_disponible',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='IdUsuario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='IdCuentaBeneficiaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_cuenta_beneficiaria', to='MiBancoVirtual.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='IdCuentaOrdenante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_cuenta_ordenante', to='MiBancoVirtual.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='IdPerfilBeneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_perfil_beneficiario', to='MiBancoVirtual.perfil'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='IdPerfilOrdenante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_perfil_ordenante', to='MiBancoVirtual.perfil'),
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfil',
        ),
    ]
