# Generated by Django 5.2.4 on 2026-06-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0021_rename_activo_categoria_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='IdTransaccion',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='Monto',
            new_name='monto',
        ),
    ]
