# Generated by Django 5.2.4 on 2026-06-28 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBancoVirtual', '0022_rename_descripcion_transaccion_descripcion_and_more'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaEfectivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('cantidad_efectivo', models.PositiveSmallIntegerField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MiBancoVirtual.cuenta')),
                ('efectivo_moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.efectivomoneda')),
            ],
            options={
                'db_table': 'cuenta_efectivo',
            },
        ),
    ]
