# Generated by Django 5.2.4 on 2026-06-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMonetaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_singular', models.CharField(max_length=50)),
                ('nombre_plural', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_unidad_monetaria',
            },
        ),
        migrations.CreateModel(
            name='EfectivoMoneda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidad_monetaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.unidadmonetaria')),
            ],
            options={
                'db_table': 'cat_efectivo_moneda',
            },
        ),
    ]
