# Generated by Django 5.2.4 on 2026-06-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efectivomoneda',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadmonetaria',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
