# Generated by Django 5.2.4 on 2026-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_profile_monto_pago_alter_profile_ultimo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, null=True),
        ),
    ]
