# Generated by Django 5.2.4 on 2026-06-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_profile_nombre'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unidad_monetaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.unidadmonetaria'),
        ),
    ]
